table '5 Satisfação Service Desk'
	lineageTag: b0637c31-2f8e-4387-acad-f21c84bcc6a7

	measure 'Total de Respostas' = SUM('5 Satisfação Service Desk'[N°])
		formatString: 0
		lineageTag: 78ec4a9f-77b8-4b6c-8f69-57d5f833c290

	measure 'Percentual de Respostas' = ```
			
			VAR RespostasNoPeriodo = [Total de Respostas] 
			VAR TotalGeralNoPeriodo =
			    CALCULATE(
			        [Total de Respostas]/100,
			        ALLEXCEPT(
			            '5 Satisfação Service Desk',
			            '5 Satisfação Service Desk'[Data da Resposta], 
			            'dCalendario'[Ano],            
			            '5 Satisfação Service Desk'[Pergunta]        
			        )
			    )
			RETURN
			    
			    IF(
			        TotalGeralNoPeriodo = 0,
			        BLANK(),
			        DIVIDE(RespostasNoPeriodo, TotalGeralNoPeriodo)
			    )
			```
		lineageTag: b5c4d35b-20b3-401f-9d82-e9ffdd4942b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Título Satisfação Service Desk' =
			
			IF (
			    HASONEVALUE ( 'dCalendario'[Ano] ),
			    SELECTEDVALUE ( 'dCalendario'[Ano]) & " (Valores Percentual %)" ,
			    "(Valores Percentual %)"
			)
		lineageTag: e6efa74d-30fc-4874-81e5-b29f3828b30f

	column 'Data da Resposta'
		dataType: dateTime
		formatString: yyyy-mm
		lineageTag: 5362f143-9b40-4c9d-813b-4a7004462d5e
		summarizeBy: none
		sourceColumn: Data da Resposta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Pergunta
		dataType: string
		lineageTag: 4c848aa9-be0c-466a-a66c-bcbe71f1588a
		summarizeBy: none
		sourceColumn: Pergunta

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Resposta
		dataType: string
		lineageTag: c644a75f-41a3-426e-9407-dc34d610ffca
		summarizeBy: none
		sourceColumn: Resposta
		sortByColumn: 'Ordem da Resposta'

		changedProperty = IsHidden

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column N°
		dataType: int64
		formatString: 0
		lineageTag: a5beff5d-f105-4408-81e9-6f5d8cead26b
		summarizeBy: sum
		sourceColumn: N°

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Ordem da Resposta'
		dataType: int64
		formatString: 0
		lineageTag: e492de66-d3c9-48ce-be40-ea082feab67a
		summarizeBy: sum
		sourceColumn: Ordem da Resposta

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	hierarchy 'Data da Resposta Hierarquia'
		lineageTag: 0c9734b9-c919-4c45-8178-c621a5486172

		level 'Data da Resposta'
			lineageTag: babce379-2e35-4db5-a925-3ca70d6fad87
			column: 'Data da Resposta'

		changedProperty = IsHidden

	partition '5 Satisfação Service Desk' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/CGTIC/", [Implementation="2.0", ViewMode="All"]),
				    #"64214c86-dbeb-4746-a0c8-bb198c583dc8" = Fonte{[Id="64214c86-dbeb-4746-a0c8-bb198c583dc8"]}[Items],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"64214c86-dbeb-4746-a0c8-bb198c583dc8",{{"Data da Resposta", type date}, {"N°", Int64.Type}}),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Tipo Alterado",{"Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "ID", "Tipo de Conteúdo", "Modificado", "Criado", "Criado por", "Modificado por", "Versão", "Anexos", "Editar", "Tipo", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Aplicativo Criado por", "Aplicativo Modificado por"}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Colunas Removidas", each true),
				    #"Duplicatas Removidas" = Table.Distinct(#"Linhas Filtradas"),
				    #"Linhas Classificadas" = Table.Sort(#"Duplicatas Removidas",{{"Resposta", Order.Ascending}}),
				    #"Coluna Condicional Adicionada" = Table.AddColumn(#"Linhas Classificadas", "Personalizar", each if [Resposta] = "Excelente" then 1 else if [Resposta] = "Muito Bom" then 2 else if [Resposta] = "Bom" then 3 else if [Resposta] = "Razoável" then 4 else if [Resposta] = "Ruim" then 5 else 99),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Coluna Condicional Adicionada",{{"Personalizar", "Ordem da Resposta"}})
				in
				    #"Colunas Renomeadas"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

