table '7 Meta Mensal Disponibilidade PJe'
	lineageTag: 2050f9a5-c0f0-4be4-8f8b-16a2e777be8c

	measure 'Meta de Disponibilidade' =
			
			SELECTEDVALUE( '7 Meta Mensal Disponibilidade PJe'[Meta Mensal])
		lineageTag: 17a2c4ed-9ae1-4304-8892-24a6360ad528

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Texto Dica Ferramenta Meta' =
			
			VAR MetaDoMes = [Meta de Disponibilidade] // Usando a medida que já criamos
			RETURN
			    IF (
			        NOT ISBLANK(MetaDoMes), // Só mostra o texto se existir uma meta para o período
			        "Meta: " & FORMAT(MetaDoMes, "0.0%") // Formata o número como percentual
			    )
		lineageTag: 092c3a75-5b0c-4228-a643-2955affc60d4

	column Mês/Ano
		dataType: dateTime
		formatString: mmmm" de "yyyy
		lineageTag: 3aa84554-3fa5-4cf5-99a4-a50950178b7c
		summarizeBy: none
		sourceColumn: Mês/Ano

		variation Variation
			isDefault
			relationship: 54afa1bd-1981-4d10-a661-a8346ed930cc
			defaultHierarchy: LocalDateTable_a8efdfa6-657f-4a7c-9d77-91a4646d5eea.'Hierarquia de datas'

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Meta Mensal'
		dataType: double
		lineageTag: 3cd781f9-e69e-488f-b0f4-3b286792f27a
		summarizeBy: sum
		sourceColumn: Meta Mensal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition '7 Meta Mensal Disponibilidade PJe' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/CGTIC/", [Implementation="2.0", ViewMode="All"]),
				    #"f7726784-4543-42b8-b5be-6fd7b3b03b24" = Fonte{[Id="f7726784-4543-42b8-b5be-6fd7b3b03b24"]}[Items],
				    #"Colunas Removidas" = Table.RemoveColumns(#"f7726784-4543-42b8-b5be-6fd7b3b03b24",{"Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "ID", "Tipo de Conteúdo", "Modificado", "Criado", "Criado por", "Modificado por", "Versão", "Anexos", "Editar", "Tipo", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Aplicativo Criado por", "Aplicativo Modificado por"})
				in
				    #"Colunas Removidas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

