table 'Cadastro de Contratos'
	lineageTag: b62c579f-e736-4857-8fee-fc22ad4e76ef

	measure 'Global (Milhões)' = SUM('Cadastro de Contratos'[Valor Global]) / 1000000
		formatString: #,0.00
		lineageTag: 99bcffc1-90b0-4b1e-84e0-b9bef6c6b8fc

	measure 'Exercicio (Milhões)' = SUM('Cadastro de Contratos'[Valor do Exercicio]) / 1000000
		formatString: #,0.00
		lineageTag: b78846c1-f2c1-4e04-a620-fb2f6c24d981

	column 'Data Início - Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 9555f21d-9174-42d7-b47c-db99e6caea5f
		summarizeBy: none
		sourceColumn: Data Início - Vigência

		variation Variation
			isDefault
			relationship: bdb7db7d-d54e-4d1f-b309-38d4305f2ff0
			defaultHierarchy: LocalDateTable_3a3d0d49-c858-4409-ba6c-b15ed3721ffb.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Final - Vigência'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 95bdc54d-9b26-4872-9d45-761d41a4abc3
		summarizeBy: none
		sourceColumn: Data Final - Vigência

		variation Variation
			isDefault
			relationship: 00de0afe-3696-452d-b716-f84ccffdb9c8
			defaultHierarchy: LocalDateTable_ceb0dfa6-2849-4fc4-ad2c-25c96b737d36.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valor Global'
		dataType: decimal
		formatString: #,0.00
		lineageTag: e14a9f15-eaa3-4085-8308-ba781f19232a
		summarizeBy: sum
		sourceColumn: Valor Global

		annotation SummarizationSetBy = Automatic

	column 'Exercício (Ano)'
		dataType: int64
		formatString: 0
		lineageTag: a8d76106-cb88-45b9-95e7-4ab94ff50a3c
		summarizeBy: none
		sourceColumn: Exercício (Ano)

		annotation SummarizationSetBy = Automatic

	column 'Valor do Exercicio'
		dataType: decimal
		formatString: #,0.00
		lineageTag: 2a54cba8-856e-43fe-a0b5-bb17bf7a39a8
		summarizeBy: sum
		sourceColumn: Valor do Exercicio

		annotation SummarizationSetBy = Automatic

	partition 'Cadastro de Contratos' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/ContrataeseOrcamento/", [Implementation="2.0", ViewMode="All"]),
				    #"aa5349e6-df2e-492b-bb52-40b894aa5ff5" = Fonte{[Id="aa5349e6-df2e-492b-bb52-40b894aa5ff5"]}[Items],
				    #"Colunas Removidas" = Table.RemoveColumns(#"aa5349e6-df2e-492b-bb52-40b894aa5ff5",{"ID", "Título", "Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "CNPJ", "Código do Credor", "Aditivo ou Contrato", "Valor Comprometido (Previsto)", "Idexcel", "Valor do Exercicio (REVISÃO - MAIO)", "Tipo de Conteúdo", "Modificado", "Criado", "Criado por", "Modificado por", "Versão", "Anexos", "Editar", "Tipo", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Aplicativo Criado por", "Aplicativo Modificado por", "Status Orçamento", "Objeto", "Número PA de Contratação", "ID Contrato", "Status", "Número do Contrato", "Nome da Empresa", "Número do Aditivo"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Data Início - Vigência", type date}, {"Data Final - Vigência", type date}}),
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado",{"Unidade Demandante"}),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"Exercício (Ano)", Int64.Type}}),
				    #"Linhas Filtradas" = Table.SelectRows(#"Tipo Alterado1", each true),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Linhas Filtradas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas em Branco Removidas1" = Table.SelectRows(#"Linhas em Branco Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Linhas Filtradas1" = Table.SelectRows(#"Linhas em Branco Removidas1", each ([#"Data Início - Vigência"] <> null)),
				    #"Linhas Filtradas2" = Table.SelectRows(#"Linhas Filtradas1", each [#"Data Final - Vigência"] <> null and [#"Data Final - Vigência"] <> ""),
				    #"Linhas Filtradas3" = Table.SelectRows(#"Linhas Filtradas2", each true),
				    #"Linhas Filtradas4" = Table.SelectRows(#"Linhas Filtradas3", each [#"Data Início - Vigência"] <> null and [#"Data Início - Vigência"] <> "")
				in
				    #"Linhas Filtradas4"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

