table Dotação
	lineageTag: e6192f68-e88d-4feb-8ca2-96b863652b9b

	column Dotação
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 51e54e5c-7c18-41d9-ba80-f061efa4af89
		summarizeBy: sum
		sourceColumn: Dotação

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 30a8c4c1-e3c0-4a2a-abac-fd9263d8956d
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	partition Dotação = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/ContrataeseOrcamento/", [Implementation="2.0", ViewMode="All"]),
				    #"0c315600-ddee-4c12-bade-a6185a499d72" = Fonte{[Id="0c315600-ddee-4c12-bade-a6185a499d72"]}[Items],
				    #"Colunas Removidas" = Table.RemoveColumns(#"0c315600-ddee-4c12-bade-a6185a499d72",{"ID pesquisa", "Título", "Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "ID", "Tipo de Conteúdo", "Criado por", "Modificado por", "Versão", "Anexos", "Editar", "Tipo", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Aplicativo Criado por", "Aplicativo Modificado por", "Elemento de Despesa", "Fonte", "Criado", "Modificado", "Projeto/Atividade"}),
				    #"Linhas em Branco Removidas" = Table.SelectRows(#"Colunas Removidas", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Linhas em Branco Removidas",{{"Ano", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

