table 'Pagamento Mensal Por Natureza'
	lineageTag: 68c5ef0b-fdf2-4414-91d7-d64c9e539f2e

	measure '% Execução' = ```
			
			VAR TotalExecutado = SUM('Pagamento Mensal Por Natureza'[Executado])
			VAR TotalPrevisto = SUM('Pagamento Mensal Por Natureza'[Previsto])
			RETURN
			    DIVIDE(
			        TotalExecutado, 
			        TotalPrevisto, 
			        0
			    )
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 2f6240a3-5847-403e-bde3-7522cb60580f

	measure 'Previsto (Milhões)' = SUM('Pagamento Mensal Por Natureza'[Previsto]) / 1000000
		formatString: #,0.00
		lineageTag: a8751224-e943-4d66-a548-de3830c22a1b

	measure 'Executado (Milhões)' = SUM('Pagamento Mensal Por Natureza'[Executado]) / 1000000
		formatString: #,0.00
		lineageTag: 134f795d-59a0-4b3e-b153-2265a9131fc1

	column 'Número do Contrato'
		dataType: string
		lineageTag: 64b32df9-ffee-4dae-adf7-57dc1a2ded8e
		summarizeBy: none
		sourceColumn: Número do Contrato

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: string
		lineageTag: 24ec6520-e0bd-4d37-8366-72f0bfdeff7b
		summarizeBy: none
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: 60e37285-3e37-44b1-bc84-6b58ae64969a
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Previsto
		dataType: decimal
		formatString: #,0.00
		lineageTag: 23175649-4afb-4513-9bd6-042930df740f
		summarizeBy: sum
		sourceColumn: Previsto

		annotation SummarizationSetBy = Automatic

	column Executado
		dataType: decimal
		formatString: #,0.00
		lineageTag: 0840f658-883f-4cdc-89e1-5b848a684e32
		summarizeBy: sum
		sourceColumn: Executado

		annotation SummarizationSetBy = Automatic

	column 'Valor não Executado'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 72ff8ec4-5699-4cce-9bcf-e631f6fe3047
		summarizeBy: sum
		sourceColumn: Valor não Executado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Percentual de Execução Mensal'
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: be2f2075-af0a-4517-8100-7368bf2eefc6
		summarizeBy: sum
		sourceColumn: Percentual de Execução Mensal

		annotation SummarizationSetBy = Automatic

	partition 'Pagamento Mensal Por Natureza' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/ContrataeseOrcamento/", [Implementation="2.0", ViewMode="All"]),
				    #"acbc49a1-0f8e-4a39-b852-ea375e31a0b8" = Fonte{[Id="acbc49a1-0f8e-4a39-b852-ea375e31a0b8"]}[Items],
				    #"Colunas Removidas" = Table.RemoveColumns(#"acbc49a1-0f8e-4a39-b852-ea375e31a0b8",{"Contrato", "Natureza", "Nº PA de Pagamento", "Anexos", "Criado por", "Modificado por", "ID", "Título", "Pressione Delete para excluir o ícone.", "ID de Ativo de Conformidade", "Tipo de Conteúdo", "Modificado", "Criado", "Versão", "Editar", "Tipo", "Contagem de Itens Filhos", "Contagem de Elementos Filho da Pasta", "Configuração do rótulo", "Rótulo de retenção", "Rótulo de retenção Aplicado", "Rótulo aplicado por", "O item é um Registro", "Aplicativo Criado por", "Aplicativo Modificado por"}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Colunas Removidas",{{"Valor não Executado", Currency.Type}, {"Ano", Int64.Type}, {"Percentual de Execução Mensal", type number}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

