table 'Cadastro de Contratos'
	lineageTag: fbae8867-975b-4999-9f7c-f101a71bad46

	measure 'Saldo Acumulativo' = ```
			
			VAR ContratoAditivoAtual = 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) & "-" & 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo])
			
			VAR AnoAtual = SELECTEDVALUE('Cadastro de Contratos'[Ano de Desembolso])
			VAR ValorGlobal = MAX('Cadastro de Contratos'[Valor Global])
			
			-- Encontrar o primeiro ano do contrato + aditivo
			VAR PrimeiroAno = 
			    CALCULATE(
			        MIN('Cadastro de Contratos'[Ano de Desembolso]),
			        ALLEXCEPT('Cadastro de Contratos', 'Cadastro de Contratos'[Número do Contrato], 'Cadastro de Contratos'[Número do Aditivo])
			    )
			
			-- Para o primeiro ano, o saldo é: Valor Global - Executado
			VAR SaldoInicial = 
			    IF(AnoAtual = PrimeiroAno, 
			        ValorGlobal - 
			        CALCULATE(
			            SUM('Cadastro de Contratos'[Executado]),
			            'Cadastro de Contratos'[Ano de Desembolso] = PrimeiroAno
			        ),
			        BLANK()
			    )
			
			-- Acumulando os valores de execução até o ano atual
			VAR ExecutadoAcumulado = 
			    CALCULATE(
			        SUM('Cadastro de Contratos'[Executado]),
			        FILTER(
			            ALL('Cadastro de Contratos'),
			            'Cadastro de Contratos'[Número do Contrato] = SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) &&
			            'Cadastro de Contratos'[Número do Aditivo] = SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo]) &&
			            'Cadastro de Contratos'[Ano de Desembolso] <= AnoAtual
			        )
			    )
			
			-- Cálculo do saldo para anos subsequentes
			RETURN 
			    IF(AnoAtual = PrimeiroAno, SaldoInicial, ValorGlobal - ExecutadoAcumulado)
			
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 2383578c-c8ed-44a2-9972-8f53c20d2a30

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '%EXEC Acumulada' = ```
			
			VAR ContratoAditivoAtual = 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) & "-" & 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo])
			
			VAR AnoAtual = SELECTEDVALUE('Cadastro de Contratos'[Ano de Desembolso])
			VAR ValorGlobal = MAX('Cadastro de Contratos'[Valor Global])
			
			-- Encontrar o primeiro ano do contrato + aditivo
			VAR PrimeiroAno = 
			    CALCULATE(
			        MIN('Cadastro de Contratos'[Ano de Desembolso]),
			        ALLEXCEPT('Cadastro de Contratos', 'Cadastro de Contratos'[Número do Contrato], 'Cadastro de Contratos'[Número do Aditivo])
			    )
			
			-- Para o primeiro ano, a % executada é Executado / Valor Global
			VAR PercentualInicial = 
			    IF(AnoAtual = PrimeiroAno, 
			        DIVIDE(
			            CALCULATE(
			                SUM('Cadastro de Contratos'[Executado]),
			                'Cadastro de Contratos'[Ano de Desembolso] = PrimeiroAno
			            ), 
			            ValorGlobal, 
			            0
			        ),
			        BLANK()
			    )
			
			-- Acumulando os valores de execução até o ano atual
			VAR ExecutadoAcumulado = 
			    CALCULATE(
			        SUM('Cadastro de Contratos'[Executado]),
			        FILTER(
			            ALL('Cadastro de Contratos'),
			            'Cadastro de Contratos'[Número do Contrato] = SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) &&
			            'Cadastro de Contratos'[Número do Aditivo] = SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo]) &&
			            'Cadastro de Contratos'[Ano de Desembolso] <= AnoAtual
			        )
			    )
			
			-- Cálculo da % para anos subsequentes
			RETURN 
			    IF(AnoAtual = PrimeiroAno, PercentualInicial, DIVIDE(ExecutadoAcumulado, ValorGlobal, 0))
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 1fea9700-6e5f-494d-8b21-bc546948ae2d

	measure '%EXEC Anual' = ```
			
			VAR ContratoAditivoAtual = 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) & "-" & 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo])
			
			VAR AnoAtual = SELECTEDVALUE('Cadastro de Contratos'[Ano de Desembolso])
			VAR ValorGlobal = MAX('Cadastro de Contratos'[Valor do Exercicio])
			
			VAR ExecutadoAnoAtual = 
			    CALCULATE(
			        SUM('Cadastro de Contratos'[Executado]),
			        FILTER(
			            ALL('Cadastro de Contratos'),
			            'Cadastro de Contratos'[Número do Contrato] = SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) &&
			            'Cadastro de Contratos'[Número do Aditivo] = SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo]) &&
			            'Cadastro de Contratos'[Ano de Desembolso] = AnoAtual
			        )
			    )
			
			RETURN 
			    DIVIDE(ExecutadoAnoAtual, ValorGlobal, 0)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 297352b2-6bbd-4c34-979d-6699e303c411

	measure 3card = ```
			
			CALCULATE(
			    SUM('Cadastro de Contratos'[Executado]),
			    YEAR('Cadastro de Contratos'[Ano de Desembolso]) = 2025
			)
			/
			[Dotação Ano Fixo 2025]
			
			```
		formatString: #,0.00%;-#,0.00%;#,0.00%
		lineageTag: 05e2f1a4-5cf7-487f-a03c-8d7ac19865da

	measure 'Executado Acumulado' = ```
			
			VAR ContratoAditivoAtual = 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) & "-" & 
			    SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo])
			
			VAR AnoAtual = SELECTEDVALUE('Cadastro de Contratos'[Ano de Desembolso])
			
			-- Acumulando os valores de execução até o ano atual
			VAR ExecutadoAcumulado = 
			    CALCULATE(
			        SUM('Cadastro de Contratos'[Executado]),
			        FILTER(
			            ALL('Cadastro de Contratos'),
			            'Cadastro de Contratos'[Número do Contrato] = SELECTEDVALUE('Cadastro de Contratos'[Número do Contrato]) &&
			            'Cadastro de Contratos'[Número do Aditivo] = SELECTEDVALUE('Cadastro de Contratos'[Número do Aditivo]) &&
			            'Cadastro de Contratos'[Ano de Desembolso] <= AnoAtual
			        )
			    )
			
			RETURN ExecutadoAcumulado
			
			```
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 7b7d3749-c92d-431d-a9ce-099868632abb

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Soma_previstoexerc = ```
			SUM('Cadastro de Contratos'[Valor do Exercicio])
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 65b9797f-22d0-4d2a-a469-100110717fa7

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Saldo Total' = ```
			[Soma_previstoexerc] - SUM('Pagamento Mensal Por Natureza'[Executado])
			
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 372db088-7bae-4ccd-a081-0aa56d181809

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure '% Execução Total' = ```
			
			DIVIDE(
			    SUM('Pagamento Mensal Por Natureza'[Executado]),
			    [Soma_previstoexerc],
			    0
			)
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: f15e4a56-fc53-4fdb-a023-24ee0ef7718f

	measure 'PREVISTO TOTAL' = SUM('Pagamento Mensal Por Natureza'[Previsto])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: dd004c34-ddb8-400a-b2c3-49e7ab00870d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Medida
		lineageTag: ad508b72-2612-4eec-afd9-d135cee4e2fd

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":null}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = Para usar caracteres especiais em um nome de medida, coloque todo o nome entre colchetes ( [] ) e adicione ] a quaisquer colchetes de fechamento no nome.

	measure previsto_exercicio_mespag = ```
			
			VAR MesAtual = MONTH(TODAY())
			VAR MesLimite = MesAtual - 2
			VAR MesLimitePositivo = IF(MesLimite > 0, MesLimite, 0)  -- Evita negativo
			
			RETURN
			    SUM('Cadastro de Contratos'[Previst exercicio por mes]) * MesLimitePositivo
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 6e8112fa-6e3f-4ed9-a955-e9db13f2825d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure Executado2 = SUM('Pagamento Mensal Por Natureza'[Executado])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 846c9508-98b0-48b7-b446-e1c4fb3be4ad

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Status
		dataType: string
		lineageTag: 265246f6-0872-459d-8fc9-508f3015ef46
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	column 'Nome da Empresa'
		dataType: string
		lineageTag: d6057a8a-736e-4698-96ca-1373ba6f859b
		summarizeBy: none
		sourceColumn: Nome da Empresa

		annotation SummarizationSetBy = Automatic

	column 'Número do Contrato'
		dataType: string
		lineageTag: ae0441ac-60db-4ee0-9604-17a82d3a56b5
		summarizeBy: none
		sourceColumn: Número do Contrato

		annotation SummarizationSetBy = Automatic

	column 'Número do Aditivo'
		dataType: string
		lineageTag: 4bf535c1-66ae-4edd-833e-00eaa9567e9d
		summarizeBy: none
		sourceColumn: Número do Aditivo

		annotation SummarizationSetBy = Automatic

	column 'Data Início - Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 8eb89139-0697-4f15-8a32-a8e6c591e8e8
		summarizeBy: none
		sourceColumn: Data Início - Vigência

		variation Variation
			isDefault
			relationship: 567acb89-0d3b-46aa-92a5-2d0065600bea
			defaultHierarchy: LocalDateTable_274dad08-b3ef-4853-89e2-a1a3717552e6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Data Final - Vigência'
		dataType: dateTime
		formatString: Short Date
		lineageTag: f38bfed9-970b-43e9-8d2c-5c279469114c
		summarizeBy: none
		sourceColumn: Data Final - Vigência

		variation Variation
			isDefault
			relationship: 2616c402-bd5f-4f71-b713-5257a4249422
			defaultHierarchy: LocalDateTable_a8c69e27-7a23-49e4-88c4-b11cad58f98a.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Valor Global'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: a398e7f0-ea1f-4006-9f1c-4c2524ba9163
		summarizeBy: sum
		sourceColumn: Valor Global

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Unidade Demandante'
		dataType: string
		lineageTag: 43103286-c8f8-4f6b-a99e-2091e975ead3
		summarizeBy: none
		sourceColumn: Unidade Demandante

		annotation SummarizationSetBy = Automatic

	column Objeto
		dataType: string
		lineageTag: e0387cc7-5e72-48d7-9fe0-b0ffda18f8ff
		summarizeBy: none
		sourceColumn: Objeto

		annotation SummarizationSetBy = Automatic

	column 'Número PA de Contratação'
		dataType: string
		lineageTag: b31698b3-b7ed-47bb-896b-f74bb8f3b357
		summarizeBy: none
		sourceColumn: Número PA de Contratação

		annotation SummarizationSetBy = Automatic

	column CNPJ
		dataType: string
		lineageTag: beada258-fe9b-4671-98bd-dd2d52dd37eb
		summarizeBy: none
		sourceColumn: CNPJ

		annotation SummarizationSetBy = Automatic

	column 'Código do Credor'
		dataType: string
		lineageTag: bd95f5d8-e264-46e3-9df1-b6fee098021c
		summarizeBy: none
		sourceColumn: Código do Credor

		annotation SummarizationSetBy = Automatic

	column 'ID Contrato'
		dataType: string
		lineageTag: 0ddd7047-4f5f-43e9-a4b4-bc07abc2c2da
		summarizeBy: none
		sourceColumn: ID Contrato

		annotation SummarizationSetBy = Automatic

	column 'Status Orçamento'
		dataType: string
		lineageTag: ae6d68dc-f81a-4fd8-9218-a5c9afa079ae
		summarizeBy: none
		sourceColumn: Status Orçamento

		annotation SummarizationSetBy = Automatic

	column Título
		dataType: string
		lineageTag: 4220c0f9-adc6-4ab9-b7cb-c48f03b75ab4
		summarizeBy: none
		sourceColumn: Título

		annotation SummarizationSetBy = Automatic

	column 'Pressione Delete para excluir o ícone.'
		dataType: string
		lineageTag: 015bb3d0-3532-4b7b-980a-ca39b73541e3
		summarizeBy: none
		sourceColumn: Pressione Delete para excluir o ícone.

		annotation SummarizationSetBy = Automatic

	column 'ID de Ativo de Conformidade'
		dataType: string
		lineageTag: a9d291e8-9a2d-45b2-a9d1-c0c98c54cd87
		summarizeBy: none
		sourceColumn: ID de Ativo de Conformidade

		annotation SummarizationSetBy = Automatic

	column 'Aditivo ou Contrato'
		dataType: string
		lineageTag: c95c40d0-a66f-4edd-a538-2af1f2345e44
		summarizeBy: none
		sourceColumn: Aditivo ou Contrato

		annotation SummarizationSetBy = Automatic

	column 'Valor Comprometido (Previsto)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 6cb6eff3-65db-4b26-854a-9dd63a437e57
		summarizeBy: sum
		sourceColumn: Valor Comprometido (Previsto)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 92182b3c-da31-4570-b9e8-4950318fba07
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Conteúdo'
		dataType: string
		lineageTag: 449bfd2e-ddde-45b4-99c5-5da55481818a
		summarizeBy: none
		sourceColumn: Tipo de Conteúdo

		annotation SummarizationSetBy = Automatic

	column Modificado
		dataType: dateTime
		formatString: General Date
		lineageTag: 1938aa0a-c6f1-4bb9-a726-6d4ee5bef545
		summarizeBy: none
		sourceColumn: Modificado

		variation Variation
			isDefault
			relationship: 6a8f934f-d54d-4bf9-9a31-807f3b31768d
			defaultHierarchy: LocalDateTable_ce799439-3442-498b-b99d-54011f50b89d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Criado
		dataType: dateTime
		formatString: General Date
		lineageTag: cddf03e3-10d2-4eea-84a6-423a8fc164d1
		summarizeBy: none
		sourceColumn: Criado

		variation Variation
			isDefault
			relationship: 51500641-9036-4df5-b801-bcf937dde63a
			defaultHierarchy: LocalDateTable_235b7faa-22d8-438b-90a3-c8a1ef3501c8.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Criado por'
		dataType: string
		lineageTag: fc309cd5-2480-4898-ab36-89283c01dfec
		summarizeBy: none
		sourceColumn: Criado por

		annotation SummarizationSetBy = Automatic

	column 'Modificado por'
		dataType: string
		lineageTag: 24544b43-5e2f-4757-ac3c-d9a86019a6aa
		summarizeBy: none
		sourceColumn: Modificado por

		annotation SummarizationSetBy = Automatic

	column Versão
		dataType: string
		lineageTag: ed03ea9b-4b2f-4362-95d9-02f9c8834639
		summarizeBy: none
		sourceColumn: Versão

		annotation SummarizationSetBy = Automatic

	column Anexos
		dataType: string
		lineageTag: 72343781-fde1-4395-8b70-3f83a707c1c9
		summarizeBy: none
		sourceColumn: Anexos

		annotation SummarizationSetBy = Automatic

	column Editar
		dataType: string
		lineageTag: 096419cc-8641-4f1c-9922-d42d42e289b9
		summarizeBy: none
		sourceColumn: Editar

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: d8479705-f943-4aa9-bed2-80b63d7b8ab7
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Contagem de Itens Filhos'
		dataType: string
		lineageTag: 7759049b-a947-464a-a0ef-36adfae53586
		summarizeBy: none
		sourceColumn: Contagem de Itens Filhos

		annotation SummarizationSetBy = Automatic

	column 'Contagem de Elementos Filho da Pasta'
		dataType: string
		lineageTag: 0f23954e-8618-4b03-ba68-b3ea01ff24e8
		summarizeBy: none
		sourceColumn: Contagem de Elementos Filho da Pasta

		annotation SummarizationSetBy = Automatic

	column 'Configuração do rótulo'
		dataType: string
		lineageTag: c2c0ff50-7dda-49e0-8dd6-bb75b55a8088
		summarizeBy: none
		sourceColumn: Configuração do rótulo

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de retenção'
		dataType: string
		lineageTag: 3170713c-bd94-476e-8043-cb7b0657ab7b
		summarizeBy: none
		sourceColumn: Rótulo de retenção

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de retenção Aplicado'
		dataType: string
		lineageTag: 7e53362b-9473-430d-8ce2-1df276682106
		summarizeBy: none
		sourceColumn: Rótulo de retenção Aplicado

		annotation SummarizationSetBy = Automatic

	column 'Rótulo aplicado por'
		dataType: string
		lineageTag: ab6b2fea-a3fd-4aaf-8f28-54809237f1cd
		summarizeBy: none
		sourceColumn: Rótulo aplicado por

		annotation SummarizationSetBy = Automatic

	column 'O item é um Registro'
		dataType: string
		lineageTag: 594e7971-4e60-4731-a40b-c0ec7a7ca44a
		summarizeBy: none
		sourceColumn: O item é um Registro

		annotation SummarizationSetBy = Automatic

	column 'Aplicativo Criado por'
		dataType: string
		lineageTag: 39139f31-805f-4ef0-b274-c4048943240c
		summarizeBy: none
		sourceColumn: Aplicativo Criado por

		annotation SummarizationSetBy = Automatic

	column 'Aplicativo Modificado por'
		dataType: string
		lineageTag: 102468c6-d4b4-4799-86d5-1060acea6c12
		summarizeBy: none
		sourceColumn: Aplicativo Modificado por

		annotation SummarizationSetBy = Automatic

	column 'Saldo Global' = ```
			[Valor Global] - [Executado2]
			
			
			```
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: a628826d-aef6-4e59-b486-949c0956e1f3
		summarizeBy: sum

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Status_Contrato = ```
			
			IF (
			    LEFT('Cadastro de Contratos'[Nome da Empresa], 3) = "DOD",
			    "Ativo",
			    IF (
			        'Cadastro de Contratos'[Data Final - Vigência] > TODAY(),
			        "Ativo",
			        "Não Ativo"
			    )
			)
			
			```
		lineageTag: bfa40130-c263-4b7e-a68e-c4f72efa3e0d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Executado = SUM('Pagamento Mensal Por Natureza'[Executado])
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 745cd582-820e-41ff-bcdb-c86e963dc379
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Ano de Desembolso'
		dataType: dateTime
		formatString: yyyy
		lineageTag: f4a1089b-f122-402c-ac35-7ebda4069683
		summarizeBy: none
		sourceColumn: Ano de Desembolso

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Valor do Exercicio'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: abaa0b2a-ede8-4574-98df-f5b0c157814c
		summarizeBy: sum
		sourceColumn: Valor do Exercicio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Idexcel
		dataType: string
		lineageTag: 7ee3e685-feb9-4d92-89e5-1f01f493b0c7
		summarizeBy: none
		sourceColumn: Idexcel

		annotation SummarizationSetBy = Automatic

	column ID_ContratoAditivo = ```
			'Cadastro de Contratos'[Número do Contrato] & "-" & 'Cadastro de Contratos'[Número do Aditivo]
			
			
			```
		lineageTag: ac16d37e-25c3-4787-8677-398cacd8309f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Valor do Exercicio (REVISÃO - MAIO)'
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 19db4247-b32e-4fbe-a4d1-c4309e22a01e
		summarizeBy: sum
		sourceColumn: Valor do Exercicio (REVISÃO - MAIO)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Previst exercicio por mes' = [Valor do Exercicio]/12
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 82acc5fc-f9a9-4de5-8f27-6f1842b4e3e3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition 'Cadastro de Contratos' = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/ContrataeseOrcamento", [Implementation="2.0", ViewMode="All"]),
				    #"aa5349e6-df2e-492b-bb52-40b894aa5ff5" = Fonte{[Id="aa5349e6-df2e-492b-bb52-40b894aa5ff5"]}[Items],
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"aa5349e6-df2e-492b-bb52-40b894aa5ff5",{{"Data Início - Vigência", type date}, {"Data Final - Vigência", type date}, {"Exercício (Ano)", type date}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"Exercício (Ano)", "Ano de Desembolso"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

