table Dotação
	lineageTag: ad205442-b345-4b9b-b9fa-adca1568813f

	measure 'Saldo fixo 2025' =
			
			VAR Resultado =
			    CALCULATE(
			        SUM('Dotação'[Saldo Dotação]),
			        'Dotação'[Ano] = "2025",
			        REMOVEFILTERS('Cadastro de Contratos'),
			        REMOVEFILTERS('Pagamento Mensal Por Natureza'),
			        REMOVEFILTERS('Dotação'),
			        REMOVEFILTERS('Valor comprometido')
			    )
			RETURN
			    COALESCE(Resultado, 0)
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: dd1ba4f3-3688-4ab1-a15d-0400ee39135d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure 'Dotação Ano Fixo 2025' = ```
			
			VAR Resultado =
			    CALCULATE(
			        SUM('Dotação'[Dotação]),
			        'Dotação'[Ano] = "2025",
			        REMOVEFILTERS('Cadastro de Contratos'),
			        REMOVEFILTERS('Pagamento Mensal Por Natureza'),
			        REMOVEFILTERS('Dotação'),
			        REMOVEFILTERS('Valor comprometido')
			    )
			RETURN
			    COALESCE(Resultado, 0)
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 60e4e203-e24a-4f7b-b2a7-e8f3015a65b1

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Projeto/Atividade
		dataType: string
		lineageTag: 9b76773b-3e7f-471c-8a5d-be1af1a994d7
		summarizeBy: none
		sourceColumn: Projeto/Atividade

		annotation SummarizationSetBy = Automatic

	column 'Elemento de Despesa'
		dataType: string
		lineageTag: baa69feb-d567-4888-b40e-13faf60d3d98
		summarizeBy: none
		sourceColumn: Elemento de Despesa

		annotation SummarizationSetBy = Automatic

	column Fonte
		dataType: string
		lineageTag: fe60a660-7b4d-4cee-8cd1-39a4b8656404
		summarizeBy: none
		sourceColumn: Fonte

		annotation SummarizationSetBy = Automatic

	column Dotação
		dataType: decimal
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 0534ed6b-2729-457f-b1f9-dce8de4e37f9
		summarizeBy: sum
		sourceColumn: Dotação

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column Ano
		dataType: string
		lineageTag: 3d759298-0fc4-432d-b2a6-05a14ddaa555
		summarizeBy: none
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column 'ID pesquisa'
		dataType: string
		lineageTag: 012f7abd-eeaa-402c-93ba-b40bd576e37f
		summarizeBy: none
		sourceColumn: ID pesquisa

		annotation SummarizationSetBy = Automatic

	column Título
		dataType: string
		lineageTag: db79024d-9307-4fea-8fd7-b372c682c46f
		summarizeBy: none
		sourceColumn: Título

		annotation SummarizationSetBy = Automatic

	column 'Pressione Delete para excluir o ícone.'
		dataType: string
		lineageTag: 8186d6e7-ff74-4831-a566-65e8172000d0
		summarizeBy: none
		sourceColumn: Pressione Delete para excluir o ícone.

		annotation SummarizationSetBy = Automatic

	column 'ID de Ativo de Conformidade'
		dataType: string
		lineageTag: c3b2502f-b9cb-4212-ab68-838330cb66ea
		summarizeBy: none
		sourceColumn: ID de Ativo de Conformidade

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 5f269e43-cfce-4369-8bb5-eda8d88eb9ea
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Tipo de Conteúdo'
		dataType: string
		lineageTag: 3f270c02-55f4-423c-812f-028da1f6f470
		summarizeBy: none
		sourceColumn: Tipo de Conteúdo

		annotation SummarizationSetBy = Automatic

	column Modificado
		dataType: dateTime
		formatString: General Date
		lineageTag: 8808dfb0-8a0b-4a72-966e-a141c762c683
		summarizeBy: none
		sourceColumn: Modificado

		variation Variation
			isDefault
			relationship: 77be2c64-cde3-464c-b105-19903c3fc378
			defaultHierarchy: LocalDateTable_20599178-2274-4e07-ac9e-0573f6d8d115.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column Criado
		dataType: dateTime
		formatString: General Date
		lineageTag: 8d7d391e-83f3-4042-9e85-32823a35e898
		summarizeBy: none
		sourceColumn: Criado

		variation Variation
			isDefault
			relationship: 216440a9-338a-44a4-b1c4-7cd1237c1ac3
			defaultHierarchy: LocalDateTable_224bfa21-c6f8-40cf-ac47-44b7ac8d0e30.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column 'Criado por'
		dataType: string
		lineageTag: c459b596-6bd2-478e-9c17-770a526a7600
		summarizeBy: none
		sourceColumn: Criado por

		annotation SummarizationSetBy = Automatic

	column 'Modificado por'
		dataType: string
		lineageTag: a61e4b9f-639f-4933-a8c3-7e062478cea4
		summarizeBy: none
		sourceColumn: Modificado por

		annotation SummarizationSetBy = Automatic

	column Versão
		dataType: string
		lineageTag: 33b28276-d3fc-4c87-9f20-86ed62ecbc9e
		summarizeBy: none
		sourceColumn: Versão

		annotation SummarizationSetBy = Automatic

	column Anexos
		dataType: string
		lineageTag: 354640ed-3f8e-4373-8f22-d386dd30bc1b
		summarizeBy: none
		sourceColumn: Anexos

		annotation SummarizationSetBy = Automatic

	column Editar
		dataType: string
		lineageTag: dc22aa0c-cfc0-4df3-beb0-25434882f712
		summarizeBy: none
		sourceColumn: Editar

		annotation SummarizationSetBy = Automatic

	column Tipo
		dataType: string
		lineageTag: 86bbbfbf-b87f-462a-90cd-c5edca3b297a
		summarizeBy: none
		sourceColumn: Tipo

		annotation SummarizationSetBy = Automatic

	column 'Contagem de Itens Filhos'
		dataType: string
		lineageTag: a50442ef-4cc9-4d49-9050-82ff6a5766bd
		summarizeBy: none
		sourceColumn: Contagem de Itens Filhos

		annotation SummarizationSetBy = Automatic

	column 'Contagem de Elementos Filho da Pasta'
		dataType: string
		lineageTag: 7b04e111-46d6-4f8f-a9be-d43efea6ebbb
		summarizeBy: none
		sourceColumn: Contagem de Elementos Filho da Pasta

		annotation SummarizationSetBy = Automatic

	column 'Configuração do rótulo'
		dataType: string
		lineageTag: 0e3fce62-ece9-431d-afe5-d4738338b638
		summarizeBy: none
		sourceColumn: Configuração do rótulo

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de retenção'
		dataType: string
		lineageTag: a79f2b3e-cf16-4d2a-b3db-970440d462e9
		summarizeBy: none
		sourceColumn: Rótulo de retenção

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de retenção Aplicado'
		dataType: string
		lineageTag: 5e35a528-09d2-4f65-8296-00b6023e8292
		summarizeBy: none
		sourceColumn: Rótulo de retenção Aplicado

		annotation SummarizationSetBy = Automatic

	column 'Rótulo aplicado por'
		dataType: string
		lineageTag: ee141b12-0088-487c-8efd-00ffa28c23df
		summarizeBy: none
		sourceColumn: Rótulo aplicado por

		annotation SummarizationSetBy = Automatic

	column 'O item é um Registro'
		dataType: string
		lineageTag: 8b6d90d5-8be9-4338-b08b-21f2688a2c0d
		summarizeBy: none
		sourceColumn: O item é um Registro

		annotation SummarizationSetBy = Automatic

	column 'Aplicativo Criado por'
		dataType: string
		lineageTag: f7581b67-5852-4bfc-9fc2-d9e5292e994d
		summarizeBy: none
		sourceColumn: Aplicativo Criado por

		annotation SummarizationSetBy = Automatic

	column 'Aplicativo Modificado por'
		dataType: string
		lineageTag: 545f1fa6-c075-4c7f-9d39-763bd3770908
		summarizeBy: none
		sourceColumn: Aplicativo Modificado por

		annotation SummarizationSetBy = Automatic

	column 'Valor Comprometido' = ```
			
			VAR SomaValores = 
			    SUMX(
			        RELATEDTABLE('Valor Comprometido'),
			        'Valor Comprometido'[Valor]
			    )
			RETURN SomaValores
			
			```
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 00b2b35e-43c4-41d7-966f-fc151784510c
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Saldo Dotação' = 'Dotação'[Dotação] - 'Dotação'[Valor Comprometido]
		formatString: "R$"\ #,0.###############;-"R$"\ #,0.###############;"R$"\ #,0.###############
		lineageTag: 81daa94f-f0fa-4ba1-9391-0e5b7bf9ec7d
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column 'Contrato Lookup' = ```
			
			VAR TabelaRelacionada =
			    FILTER(
			        'valor comprometido',
			        'Valor Comprometido'[ID projeto.lookupValue] = 'dotação'[ID Pesquisa]
			    )
			RETURN
			    CALCULATE(
			        FIRSTNONBLANK('valor comprometido'[Contrato_.lookupValue], 1),
			        TabelaRelacionada
			    )
			
			```
		lineageTag: dbacf889-4c6b-4aa6-a670-4b9ed99f2579
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Dotação = m
		mode: import
		source =
				let
				    Fonte = SharePoint.Tables("https://tjbacotec.sharepoint.com/sites/ContrataeseOrcamento", [Implementation="2.0", ViewMode="All"]),
				    #"0c315600-ddee-4c12-bade-a6185a499d72" = Fonte{[Id="0c315600-ddee-4c12-bade-a6185a499d72"]}[Items]
				in
				    #"0c315600-ddee-4c12-bade-a6185a499d72"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

