table MonthlyMetrics
	lineageTag: aa111111-1111-1111-1111-111111111111

	measure TotalViews = SUM(MonthlyMetrics[Views])
		formatString: #,##0
		lineageTag: aa222222-2222-2222-2222-222222222222

	measure TotalVisits = SUM(MonthlyMetrics[Visits])
		formatString: #,##0
		lineageTag: aa333333-3333-3333-3333-333333333333

	measure TotalNewUsers = SUM(MonthlyMetrics[NewUsers])
		formatString: #,##0
		lineageTag: aa444444-4444-4444-4444-444444444444

	measure TotalActiveUsers = SUM(MonthlyMetrics[ActiveUsers])
		formatString: #,##0
		lineageTag: aa555555-5555-5555-5555-555555555555

	measure HtmlKpiViews =
			VAR _val = [TotalViews]
			VAR _pct = "+11.01%"
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}.kb{padding:1px;border-radius:16px;background:linear-gradient(270deg,#009ef7,#7239ea,#009ef7);background-size:300% 300%;animation:br 4s ease infinite}.ki{border-radius:15px;background:#1e1e2d}</style>" &
			"<div class='kb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;'>" &
			"<div class='ki' style='width:100%;height:100%;box-sizing:border-box;padding:20px 24px;display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>" &
			"<span style='font-size:13px;color:#565674;font-weight:500;'>Views</span>" &
			"<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#009ef7' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg></div>" &
			"<div style='display:flex;align-items:baseline;gap:12px;'>" &
			"<span style='font-size:32px;font-weight:700;color:#fff;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:13px;color:#50cd89;font-weight:500;'>" & _pct & " ↗</span></div>" &
			"</div></div>"
		lineageTag: aa666666-6666-6666-6666-666666666666

	measure HtmlKpiVisits =
			VAR _val = [TotalVisits]
			VAR _pct = "-0.03%"
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}.kb{padding:1px;border-radius:16px;background:linear-gradient(270deg,#50cd89,#009ef7,#50cd89);background-size:300% 300%;animation:br 4s ease infinite}.ki{border-radius:15px;background:#1e1e2d}</style>" &
			"<div class='kb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;'>" &
			"<div class='ki' style='width:100%;height:100%;box-sizing:border-box;padding:20px 24px;display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>" &
			"<span style='font-size:13px;color:#565674;font-weight:500;'>Visits</span>" &
			"<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#50cd89' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg></div>" &
			"<div style='display:flex;align-items:baseline;gap:12px;'>" &
			"<span style='font-size:32px;font-weight:700;color:#fff;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:13px;color:#f1416c;font-weight:500;'>" & _pct & " ↘</span></div>" &
			"</div></div>"
		lineageTag: aa777777-7777-7777-7777-777777777777

	measure HtmlKpiNewUsers =
			VAR _val = [TotalNewUsers]
			VAR _pct = "+15.03%"
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}.kb{padding:1px;border-radius:16px;background:linear-gradient(270deg,#f1416c,#7239ea,#f1416c);background-size:300% 300%;animation:br 4s ease infinite}.ki{border-radius:15px;background:#1e1e2d}</style>" &
			"<div class='kb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;'>" &
			"<div class='ki' style='width:100%;height:100%;box-sizing:border-box;padding:20px 24px;display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>" &
			"<span style='font-size:13px;color:#565674;font-weight:500;'>New Users</span>" &
			"<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#f1416c' stroke-width='2' stroke-linecap='round'><path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><line x1='19' y1='8' x2='19' y2='14'/><line x1='22' y1='11' x2='16' y2='11'/></svg></div>" &
			"<div style='display:flex;align-items:baseline;gap:12px;'>" &
			"<span style='font-size:32px;font-weight:700;color:#fff;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:13px;color:#50cd89;font-weight:500;'>" & _pct & " ↗</span></div>" &
			"</div></div>"
		lineageTag: aa888888-8888-8888-8888-888888888888

	measure HtmlKpiActiveUsers =
			VAR _val = [TotalActiveUsers]
			VAR _pct = "+6.08%"
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}.kb{padding:1px;border-radius:16px;background:linear-gradient(270deg,#7239ea,#009ef7,#7239ea);background-size:300% 300%;animation:br 4s ease infinite}.ki{border-radius:15px;background:#1e1e2d}</style>" &
			"<div class='kb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;'>" &
			"<div class='ki' style='width:100%;height:100%;box-sizing:border-box;padding:20px 24px;display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;'>" &
			"<span style='font-size:13px;color:#565674;font-weight:500;'>Active Users</span>" &
			"<svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#7239ea' stroke-width='2' stroke-linecap='round'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg></div>" &
			"<div style='display:flex;align-items:baseline;gap:12px;'>" &
			"<span style='font-size:32px;font-weight:700;color:#fff;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:13px;color:#50cd89;font-weight:500;'>" & _pct & " ↗</span></div>" &
			"</div></div>"
		lineageTag: aa999999-9999-9999-9999-999999999999

	measure LightKpiViews =
			VAR _val = [TotalViews]
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#3B82F6;border-radius:16px;padding:24px;color:white;position:relative;overflow:hidden;'>" &
			"<div style='position:absolute;top:20px;right:20px;width:32px;height:32px;border-radius:10px;background:rgba(255,255,255,0.2);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg></div>" &
			"<div style='font-size:13px;font-weight:500;color:rgba(219,234,254,1);margin-bottom:4px;'>Views</div>" &
			"<div style='display:flex;align-items:baseline;justify-content:space-between;margin-top:12px;'>" &
			"<span style='font-size:30px;font-weight:600;letter-spacing:-0.5px;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:12px;font-weight:500;color:rgba(219,234,254,0.85);'>+11.01%</span></div></div>"
		lineageTag: bb111111-1111-1111-1111-111111111111

	measure LightKpiVisits =
			VAR _val = [TotalVisits]
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#1F2937;border-radius:16px;padding:24px;color:white;position:relative;overflow:hidden;'>" &
			"<div style='position:absolute;top:20px;right:20px;width:32px;height:32px;border-radius:10px;background:rgba(255,255,255,0.1);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round'><polyline points='23 18 13.5 8.5 8.5 13.5 1 6'/><polyline points='17 18 23 18 23 12'/></svg></div>" &
			"<div style='font-size:13px;font-weight:500;color:rgba(156,163,175,1);margin-bottom:4px;'>Visits</div>" &
			"<div style='display:flex;align-items:baseline;justify-content:space-between;margin-top:12px;'>" &
			"<span style='font-size:30px;font-weight:600;letter-spacing:-0.5px;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:12px;font-weight:500;color:rgba(156,163,175,0.85);'>-0.03%</span></div></div>"
		lineageTag: bb222222-2222-2222-2222-222222222222

	measure LightKpiNewUsers =
			VAR _val = [TotalNewUsers]
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#3B82F6;border-radius:16px;padding:24px;color:white;position:relative;overflow:hidden;'>" &
			"<div style='position:absolute;top:20px;right:20px;width:32px;height:32px;border-radius:10px;background:rgba(255,255,255,0.2);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg></div>" &
			"<div style='font-size:13px;font-weight:500;color:rgba(219,234,254,1);margin-bottom:4px;'>New Users</div>" &
			"<div style='display:flex;align-items:baseline;justify-content:space-between;margin-top:12px;'>" &
			"<span style='font-size:30px;font-weight:600;letter-spacing:-0.5px;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:12px;font-weight:500;color:rgba(219,234,254,0.85);'>+15.03%</span></div></div>"
		lineageTag: bb333333-3333-3333-3333-333333333333

	measure LightKpiActiveUsers =
			VAR _val = [TotalActiveUsers]
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#1F2937;border-radius:16px;padding:24px;color:white;position:relative;overflow:hidden;'>" &
			"<div style='position:absolute;top:20px;right:20px;width:32px;height:32px;border-radius:10px;background:rgba(255,255,255,0.1);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg></div>" &
			"<div style='font-size:13px;font-weight:500;color:rgba(156,163,175,1);margin-bottom:4px;'>Active Users</div>" &
			"<div style='display:flex;align-items:baseline;justify-content:space-between;margin-top:12px;'>" &
			"<span style='font-size:30px;font-weight:600;letter-spacing:-0.5px;'>" & FORMAT(_val, "#,##0") & "</span>" &
			"<span style='font-size:12px;font-weight:500;color:rgba(156,163,175,0.85);'>+6.08%</span></div></div>"
		lineageTag: bb444444-4444-4444-4444-444444444444

	column Month
		lineageTag: ab111111-1111-1111-1111-111111111111
		isNameInferred
		sourceColumn: [Month]

	column Views
		lineageTag: ab222222-2222-2222-2222-222222222222
		isNameInferred
		sourceColumn: [Views]

	column Visits
		lineageTag: ab333333-3333-3333-3333-333333333333
		isNameInferred
		sourceColumn: [Visits]

	column NewUsers
		lineageTag: ab444444-4444-4444-4444-444444444444
		isNameInferred
		sourceColumn: [NewUsers]

	column ActiveUsers
		lineageTag: ab555555-5555-5555-5555-555555555555
		isNameInferred
		sourceColumn: [ActiveUsers]

	column ThisYear
		lineageTag: ab666666-6666-6666-6666-666666666666
		isNameInferred
		sourceColumn: [ThisYear]

	column LastYear
		lineageTag: ab777777-7777-7777-7777-777777777777
		isNameInferred
		sourceColumn: [LastYear]

	partition MonthlyMetrics = calculated
		mode: import
		source =
				DATATABLE(
					"Month", STRING,
					"Views", DOUBLE,
					"Visits", DOUBLE,
					"NewUsers", DOUBLE,
					"ActiveUsers", DOUBLE,
					"ThisYear", DOUBLE,
					"LastYear", DOUBLE,
					{
						{"Jan", 1200, 620, 38, 380, 10000, 8000},
						{"Feb", 980, 510, 28, 310, 15000, 12000},
						{"Mar", 1350, 680, 42, 420, 12000, 18000},
						{"Apr", 890, 440, 22, 280, 28000, 15000},
						{"May", 1100, 560, 35, 350, 25000, 20000},
						{"Jun", 745, 361, 41, 278, 22000, 17000},
						{"Jul", 0, 0, 0, 0, 30000, 22000}
					}
				)

