table MasterClassData
	lineageTag: e8d7c6b5-a4b3-c2d1-e9f0-1234567890ab

	measure TotalRevenueMC = SUM(MasterClassData[Revenue])
		formatString: $#,##0
		lineageTag: f9e8d7c6-b5a4-0000-0001-1234567890ab

	measure TotalCostMC = SUM(MasterClassData[Cost])
		formatString: $#,##0
		lineageTag: f9e8d7c6-b5a4-0000-0002-1234567890ab

	measure AvgProgressMC = AVERAGE(MasterClassData[Progress])
		formatString: 0.0%
		lineageTag: f9e8d7c6-b5a4-0000-0003-1234567890ab

	measure MarginMC = DIVIDE([TotalRevenueMC] - [TotalCostMC], [TotalRevenueMC], 0)
		formatString: 0.0%
		lineageTag: f9e8d7c6-b5a4-0000-0004-1234567890ab

	measure McHtmlSidebar = "<div style='width: 100%; height: 100%; background: linear-gradient(180deg, rgba(13, 27, 42, 0.95), rgba(27, 38, 59, 0.8)); backdrop-filter: blur(15px); border-right: 1px solid rgba(100, 255, 218, 0.1); display: flex; flex-direction: column; align-items: center; padding: 32px 0;'><div style='color: #64FFDA; margin-bottom: 64px;'><svg width='32' height='32' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'><polygon points='12 2 2 7 12 12 22 7 12 2'></polygon><polyline points='2 17 12 22 22 17'></polyline><polyline points='2 12 12 17 22 12'></polyline></svg></div><div style='display: flex; flex-direction: column; gap: 32px; color: #8892B0;'><div style='cursor: pointer; transition: color 0.3s ease;' onmouseover=""this.style.color='#64FFDA'"" onmouseout=""this.style.color='#8892B0'""><svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><rect x='3' y='3' width='18' height='18' rx='2' ry='2'></rect><line x1='3' y1='9' x2='21' y2='9'></line><line x1='9' y1='21' x2='9' y2='9'></line></svg></div><div style='cursor: pointer; transition: color 0.3s ease; color: #64FFDA;'><svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><path d='M21.21 15.89A10 10 0 1 1 8 2.83'></path><path d='M22 12A10 10 0 0 0 12 2v10z'></path></svg></div><div style='cursor: pointer; transition: color 0.3s ease;' onmouseover=""this.style.color='#64FFDA'"" onmouseout=""this.style.color='#8892B0'""><svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'></path><circle cx='9' cy='7' r='4'></circle><path d='M23 21v-2a4 4 0 0 0-3-3.87'></path><path d='M16 3.13a4 4 0 0 1 0 7.75'></path></svg></div></div></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0001-1234567890a1

	measure McHtmlHeader = "<div style='width: 100%; height: 100%; display: flex; justify-content: space-between; align-items: center; font-family: ""Segoe UI"", Tahoma, sans-serif;'><div><h1 style='margin: 0; font-size: 28px; font-weight: 600; color: #E2E8F0; text-shadow: 0 0 20px rgba(100, 255, 218, 0.3);'>Alpha Protocol Overview</h1><p style='margin: 4px 0 0 0; font-size: 14px; color: #8892B0;'>Executive Summary • Enterprise Division</p></div></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0002-1234567890a2

	measure McHtmlKpiRev =
			VAR Val = FORMAT([TotalRevenueMC] / 1000000, "$0.00M")
			VAR Target = "$8.50M"
			RETURN "<div style='width: 100%; height: 100%; background: linear-gradient(135deg, rgba(27, 38, 59, 0.4), rgba(13, 27, 42, 0.8)); backdrop-filter: blur(8px); border: 1px solid rgba(136, 146, 176, 0.15); border-radius: 12px; padding: 24px; box-sizing: border-box; font-family: ""Segoe UI"", Tahoma, sans-serif; position: relative; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.2);'><div style='position:absolute; top:-20px; right:-20px; width:100px; height:100px; background:radial-gradient(circle, rgba(100,255,218,0.2) 0%, transparent 70%); border-radius:50%;'></div><p style='margin:0; font-size:12px; color:#8892B0; text-transform:uppercase; letter-spacing:1px; font-weight:600;'>Total Revenue</p><p style='margin:8px 0 4px 0; font-size:32px; font-weight:700; color:#E2E8F0;'>" & Val & "</p><p style='margin:0; font-size:12px; color:#64FFDA; display:flex; align-items:center; gap:4px;'><svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'></polyline><polyline points='17 6 23 6 23 12'></polyline></svg>12.4% vs Target (" & Target & ")</p></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0003-1234567890a3

	measure McHtmlKpiMargin =
			VAR Val = FORMAT([MarginMC], "0.0%")
			RETURN "<div style='width: 100%; height: 100%; background: linear-gradient(135deg, rgba(27, 38, 59, 0.4), rgba(13, 27, 42, 0.8)); backdrop-filter: blur(8px); border: 1px solid rgba(136, 146, 176, 0.15); border-radius: 12px; padding: 24px; box-sizing: border-box; font-family: ""Segoe UI"", Tahoma, sans-serif; position: relative; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.2);'><div style='position:absolute; top:-20px; right:-20px; width:100px; height:100px; background:radial-gradient(circle, rgba(255,107,107,0.15) 0%, transparent 70%); border-radius:50%;'></div><p style='margin:0; font-size:12px; color:#8892B0; text-transform:uppercase; letter-spacing:1px; font-weight:600;'>Net Margin</p><p style='margin:8px 0 4px 0; font-size:32px; font-weight:700; color:#E2E8F0;'>" & Val & "</p><p style='margin:0; font-size:12px; color:#FF6B6B; display:flex; align-items:center; gap:4px;'><svg width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><polyline points='23 18 13.5 8.5 8.5 13.5 1 6'></polyline><polyline points='17 18 23 18 23 12'></polyline></svg>-2.1% (Logistics overload)</p></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0004-1234567890a4

	measure McHtmlKpiActive =
			VAR Val = COUNTROWS(FILTER(MasterClassData, MasterClassData[Progress] < 1))
			VAR Total = COUNTROWS(MasterClassData)
			RETURN "<div style='width: 100%; height: 100%; background: linear-gradient(135deg, rgba(27, 38, 59, 0.4), rgba(13, 27, 42, 0.8)); backdrop-filter: blur(8px); border: 1px solid rgba(136, 146, 176, 0.15); border-radius: 12px; padding: 24px; box-sizing: border-box; font-family: ""Segoe UI"", Tahoma, sans-serif; position: relative; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.2);'><div style='position:absolute; top:-20px; right:-20px; width:100px; height:100px; background:radial-gradient(circle, rgba(94,114,228,0.2) 0%, transparent 70%); border-radius:50%;'></div><p style='margin:0; font-size:12px; color:#8892B0; text-transform:uppercase; letter-spacing:1px; font-weight:600;'>Active Projects</p><p style='margin:8px 0 4px 0; font-size:32px; font-weight:700; color:#E2E8F0;'>" & Val & "</p><p style='margin:0; font-size:12px; color:#8892B0; display:flex; align-items:center; gap:4px;'>" & (Total - Val) & " completed this cycle</p></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0005-1234567890a5

	measure McHtmlChartBg1 = "<div style='width: 100%; height: 100%; background: linear-gradient(180deg, rgba(13, 27, 42, 0.6), rgba(27, 38, 59, 0.4)); backdrop-filter: blur(4px); border: 1px solid rgba(136, 146, 176, 0.1); border-radius: 12px; box-shadow: inset 0 0 40px rgba(0,0,0,0.2);'></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0006-1234567890a6

	measure McDrawerBg = "<div style='background: linear-gradient(135deg, rgba(13, 27, 42, 0.98), rgba(27, 38, 59, 0.95)); backdrop-filter: blur(15px); border-left: 1px solid rgba(100, 255, 218, 0.2); width: 100%; height: 100%; box-sizing: border-box; padding: 32px 24px; box-shadow: -10px 0 30px rgba(0,0,0,0.5); color: #E2E8F0; font-family: ""Segoe UI"", Tahoma, sans-serif;'><h2 style='margin:0 0 32px 0; font-size:18px; font-weight:500; letter-spacing:1px; color:#64FFDA; display:flex; align-items:center; gap:8px;'><svg width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3'></polygon></svg>ANALYSIS FILTERS</h2></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0007-1234567890a7

	measure McBtnOpen = "<div style='width: 100%; height: 100%; background: rgba(100, 255, 218, 0.1); border: 1px solid rgba(100, 255, 218, 0.3); border-radius: 8px; display: flex; justify-content: center; align-items: center; color: #64FFDA; cursor: pointer; transition: all 0.2s ease;'><svg width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3'></polygon></svg></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0008-1234567890a8

	measure McBtnClose = "<div style='width: 100%; height: 100%; background: transparent; border: none; display: flex; justify-content: center; align-items: center; color: #8892B0; cursor: pointer;'><svg width='24' height='24' viewBox='0 0 24 24' fill='none' stroke='currentColor' stroke-width='2'><line x1='18' y1='6' x2='6' y2='18'></line><line x1='6' y1='6' x2='18' y2='18'></line></svg></div>"
		lineageTag: f9e8d7c6-b5a4-1000-0009-1234567890a9

	column ID
		dataType: string
		lineageTag: b0c1d2e3-0001-0000-0000-000000000001
		isNameInferred
		sourceColumn: [ID]

	column Project
		dataType: string
		lineageTag: b0c1d2e3-0002-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Project]

	column Category
		dataType: string
		lineageTag: b0c1d2e3-0003-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Category]

	column Revenue
		dataType: double
		lineageTag: b0c1d2e3-0004-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Revenue]

	column Cost
		dataType: double
		lineageTag: b0c1d2e3-0005-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Cost]

	column Progress
		dataType: double
		lineageTag: b0c1d2e3-0006-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Progress]

	column StartDate
		dataType: dateTime
		lineageTag: b0c1d2e3-0007-0000-0000-000000000001
		isNameInferred
		sourceColumn: [StartDate]

	column EndDate
		dataType: dateTime
		lineageTag: b0c1d2e3-0008-0000-0000-000000000001
		isNameInferred
		sourceColumn: [EndDate]

	column Owner
		dataType: string
		lineageTag: b0c1d2e3-0009-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Owner]

	column Status
		dataType: string
		lineageTag: b0c1d2e3-0010-0000-0000-000000000001
		isNameInferred
		sourceColumn: [Status]

	partition MasterClassData = calculated
		mode: import
		source =
				DATATABLE(
					"ID", STRING, "Project", STRING, "Category", STRING, "Revenue", DOUBLE, "Cost", DOUBLE,
					"Progress", DOUBLE, "StartDate", DATETIME, "EndDate", DATETIME, "Owner", STRING, "Status", STRING,
					{
						{"P01", "Nexus API Revamp", "Engineering", 1250000, 850000, 1.0, "2025-01-15", "2025-06-30", "Sarah J", "Completed"},
						{"P02", "CyberSec Audit", "Security", 850000, 320000, 0.45, "2025-10-01", "2026-03-15", "Marcus T", "In Progress"},
						{"P03", "Cloud Migration Q3", "Infrastructure", 3500000, 2100000, 0.82, "2025-07-01", "2026-02-28", "Elena R", "In Progress"},
						{"P04", "Data Lake Beta", "Data", 2100000, 1950000, 0.15, "2026-01-10", "2026-11-30", "David M", "At Risk"},
						{"P05", "Mobile App v2.0", "Engineering", 1850000, 1200000, 0.95, "2025-04-01", "2026-01-15", "Sarah J", "In Progress"},
						{"P06", "Fraud ML Model", "Data", 950000, 410000, 1.0, "2025-02-15", "2025-08-30", "Elena R", "Completed"},
						{"P07", "Zero Trust Net", "Security", 1750000, 1150000, 0.05, "2026-02-01", "2026-12-15", "Marcus T", "Started"},
						{"P08", "Global Load Balancer", "Infrastructure", 4200000, 3100000, 0.60, "2025-09-01", "2026-05-30", "David M", "In Progress"},
						{"P09", "Customer Portal", "Engineering", 2300000, 1600000, 0.35, "2025-11-15", "2026-08-30", "Sarah J", "In Progress"},
						{"P10", "GDPR Compliance", "Security", 650000, 480000, 1.0, "2025-01-01", "2025-04-30", "Marcus T", "Completed"}
					}
				)

