table SampleData
	lineageTag: a1b2c3d4-e5f6-7890-abcd-ef1234567890

	measure TotalReceita = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Receita Total")
		formatString: R$ #,##0
		lineageTag: e5f6a7b8-c9d0-1234-efab-345678901234

	measure UsuariosAtivos = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Usuários Ativos")
		formatString: #,##0
		lineageTag: f6a7b8c9-d0e1-2345-fabc-456789012345

	measure Satisfacao = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Satisfação") / 100
		formatString: 0.0%
		lineageTag: a7b8c9d0-e1f2-3456-abcd-567890123456

	measure HtmlCardReceita =
			VAR _valor = [TotalReceita]
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Receita Total")
			VAR _percent = DIVIDE(_valor, _meta, 0) * 100
			RETURN
			"<div style='font-family: Segoe UI, sans-serif; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 16px; padding: 24px; color: white; box-shadow: 0 8px 32px rgba(102,126,234,0.3);'>" &
			"<p style='margin:0; font-size:12px; opacity:0.8; text-transform:uppercase; letter-spacing:1px;'>Receita Total</p>" &
			"<h2 style='margin:8px 0; font-size:32px; font-weight:700;'>R$ " & FORMAT(_valor, "#,##0") & "</h2>" &
			"<div style='background:rgba(255,255,255,0.2); border-radius:8px; height:6px; margin-top:12px;'>" &
			"<div style='background:white; border-radius:8px; height:6px; width:" & FORMAT(_percent, "0") & "%;'></div></div>" &
			"<p style='margin:4px 0 0; font-size:11px; opacity:0.7;'>" & FORMAT(_percent, "0.0") & "% da meta</p>" &
			"</div>"
		lineageTag: b8c9d0e1-f2a3-4567-bcde-678901234567

	measure HtmlGlassCard =
			VAR _valor = [TotalReceita]
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Receita Total")
			VAR _percent = DIVIDE(_valor - _meta, _meta, 0) * 100
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes gp{0%,100%{text-shadow:0 0 20px rgba(99,102,241,0.3)}50%{text-shadow:0 0 40px rgba(99,102,241,0.8),0 0 60px rgba(99,102,241,0.4)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#6366F1,#06B6D4,#EC4899,#8B5CF6);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.gn{animation:gp 2s ease-in-out infinite}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:min(24px,4vh) min(24px,4vw);display:flex;flex-direction:column;justify-content:center;position:relative;overflow:hidden;'>" &
			"<div style='position:absolute;top:-50%;right:-50%;width:100%;height:100%;background:radial-gradient(circle,rgba(99,102,241,0.15) 0%,transparent 70%);'></div>" &
			"<div style='display:flex;align-items:center;gap:8px;margin:0 0 min(12px,2vh);position:relative;'><svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='#A78BFA' stroke-width='2' stroke-linecap='round'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg><span style='font-size:min(11px,2.5vw);text-transform:uppercase;letter-spacing:1.5px;color:rgba(255,255,255,0.5);'>Receita Mensal</span></div>" &
			"<div class='gn' style='font-size:min(36px,8vw);font-weight:700;background:linear-gradient(135deg,#6366F1,#A78BFA);-webkit-background-clip:text;-webkit-text-fill-color:transparent;margin-bottom:min(16px,3vh);position:relative;'>R$ " & FORMAT(_valor, "#,##0") & "</div>" &
			"<div style='display:flex;align-items:center;gap:6px;font-size:min(13px,2.5vw);color:#4ADE80;position:relative;'>" &
			"<span style='padding:2px 6px;background:rgba(74,222,128,0.1);border-radius:4px;font-size:min(11px,2vw);'>▲ " & FORMAT(ABS(_percent), "0.0") & "%</span> vs. mês anterior</div></div></div>"
		lineageTag: 11111111-1111-1111-1111-111111111111

	measure HtmlNeonCard =
			VAR _valor = [UsuariosAtivos]
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Usuários Ativos")
			VAR _percent = DIVIDE(_valor - _meta, _meta, 0) * 100
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes gp{0%,100%{text-shadow:0 0 15px rgba(6,182,212,0.3)}50%{text-shadow:0 0 30px rgba(6,182,212,0.8)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#06B6D4,#8B5CF6,#EC4899,#06B6D4);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.gn{animation:gp 2s ease-in-out infinite}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:min(24px,4vh) min(24px,4vw);display:flex;flex-direction:column;justify-content:center;position:relative;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:min(20px,3vh);'>" &
			"<div style='width:min(40px,8vw);height:min(40px,8vw);border-radius:12px;display:flex;align-items:center;justify-content:center;background:rgba(6,182,212,0.15);box-shadow:0 0 20px rgba(6,182,212,0.1);'><svg width='20' height='20' viewBox='0 0 24 24' fill='none' stroke='#06B6D4' stroke-width='2' stroke-linecap='round'><path d='M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M22 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg></div>" &
			"<span style='font-size:min(11px,2.5vw);padding:4px 10px;border-radius:20px;background:rgba(74,222,128,0.1);color:#4ADE80;font-weight:500;'>+" & FORMAT(ABS(_percent), "0.0") & "%</span></div>" &
			"<div class='gn' style='font-size:min(32px,7vw);font-weight:700;margin-bottom:4px;'>" & FORMAT(_valor, "#,##0") & "</div>" &
			"<div style='font-size:min(12px,2.5vw);color:#6B7280;'>Usuários Ativos</div>" &
			"<div style='position:absolute;bottom:0;left:16px;right:16px;height:2px;background:linear-gradient(90deg,#06B6D4,#8B5CF6,#EC4899);border-radius:2px;'></div></div></div>"
		lineageTag: 22222222-2222-2222-2222-222222222222

	measure HtmlProgressCard =
			VAR _valor = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Receita Total")
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Receita Total")
			VAR _percent = DIVIDE(_valor, _meta, 0) * 100
			VAR _falta = _meta - _valor
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes fb{from{width:0%}}@keyframes gp{0%,100%{text-shadow:0 0 15px rgba(139,92,246,0.3)}50%{text-shadow:0 0 30px rgba(139,92,246,0.8)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#8B5CF6,#6366F1,#06B6D4,#8B5CF6);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.gn{animation:gp 2s ease-in-out infinite}.ab{animation:fb 1.5s ease-out forwards}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:min(24px,4vh) min(24px,4vw);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:min(20px,3vh);'>" &
			"<div><div style='display:flex;align-items:center;gap:6px;margin:0 0 8px;'><svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round'><circle cx='12' cy='12' r='10'/><circle cx='12' cy='12' r='6'/><circle cx='12' cy='12' r='2'/></svg><span style='font-size:min(13px,2.5vw);color:#9CA3AF;'>Meta de Vendas</span></div>" &
			"<div class='gn' style='font-size:min(28px,6vw);font-weight:700;'>R$ " & FORMAT(_valor, "#,##0") & "</div></div>" &
			"<div style='font-size:min(24px,5vw);font-weight:600;color:#8B5CF6;'>" & FORMAT(_percent, "0") & "%</div></div>" &
			"<div style='background:rgba(255,255,255,0.06);border-radius:6px;height:min(8px,1.5vh);overflow:hidden;margin-bottom:min(12px,2vh);'>" &
			"<div class='ab' style='height:100%;border-radius:6px;background:linear-gradient(90deg,#8B5CF6,#6366F1,#06B6D4);width:" & FORMAT(_percent, "0") & "%;'></div></div>" &
			"<div style='display:flex;justify-content:space-between;font-size:min(11px,2vw);color:#6B7280;'>" &
			"<span>R$ " & FORMAT(_valor / 1000, "#,##0") & "k de R$ " & FORMAT(_meta / 1000, "#,##0") & "k</span>" &
			"<span>Faltam R$ " & FORMAT(ABS(_falta) / 1000, "#,##0") & "k</span></div></div></div>"
		lineageTag: 33333333-3333-3333-3333-333333333333

	measure HtmlSparkCard =
			VAR _valor = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Ticket Médio")
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes fb{from{height:0%}}@keyframes gp{0%,100%{text-shadow:0 0 15px rgba(99,102,241,0.3)}50%{text-shadow:0 0 30px rgba(99,102,241,0.8)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#6366F1,#8B5CF6,#4ADE80,#6366F1);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.gn{animation:gp 2s ease-in-out infinite}.sb{animation:fb 0.8s ease-out both}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:min(24px,4vh) min(24px,4vw);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;align-items:center;gap:6px;margin:0 0 min(6px,1vh);'><svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#6366F1' stroke-width='2' stroke-linecap='round'><line x1='18' y1='20' x2='18' y2='10'/><line x1='12' y1='20' x2='12' y2='4'/><line x1='6' y1='20' x2='6' y2='14'/></svg><span style='font-size:min(12px,2.5vw);color:#6B7280;'>Vendas Semanais</span></div>" &
			"<div style='display:flex;justify-content:space-between;align-items:flex-end;margin-bottom:min(16px,3vh);'>" &
			"<div class='gn' style='font-size:min(28px,6vw);font-weight:700;'>R$ " & FORMAT(_valor * 149, "#,##0") & "</div>" &
			"<div style='font-size:min(13px,2.5vw);color:#4ADE80;font-weight:500;'>+8.3%</div></div>" &
			"<div style='display:flex;align-items:flex-end;gap:3px;height:min(40px,15vh);flex:1;'>" &
			"<div class='sb' style='flex:1;height:45%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0s;'></div>" &
			"<div class='sb' style='flex:1;height:60%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.05s;'></div>" &
			"<div class='sb' style='flex:1;height:35%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.1s;'></div>" &
			"<div class='sb' style='flex:1;height:75%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.15s;'></div>" &
			"<div class='sb' style='flex:1;height:55%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.2s;'></div>" &
			"<div class='sb' style='flex:1;height:90%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.25s;'></div>" &
			"<div class='sb' style='flex:1;height:70%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.3s;'></div>" &
			"<div class='sb' style='flex:1;height:85%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.35s;'></div>" &
			"<div class='sb' style='flex:1;height:65%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.4s;'></div>" &
			"<div class='sb' style='flex:1;height:95%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.45s;'></div>" &
			"<div class='sb' style='flex:1;height:80%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.5s;'></div>" &
			"<div class='sb' style='flex:1;height:100%;background:linear-gradient(to top,rgba(99,102,241,0.3),rgba(99,102,241,0.8));border-radius:3px 3px 0 0;animation-delay:0.55s;'></div>" &
			"</div></div></div>"
		lineageTag: 44444444-4444-4444-4444-444444444444

	measure HtmlStatusCard =
			VAR _satisf = [Satisfacao] * 100
			VAR _conversao = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Conversão")
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes p{0%,100%{opacity:1;transform:scale(1)}50%{opacity:.6;transform:scale(.8)}}@keyframes fs{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#4ADE80,#06B6D4,#8B5CF6,#4ADE80);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.pulse{animation:p 2s infinite}.fi{animation:fs 0.5s ease-out both}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:min(24px,4vh) min(24px,4vw);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;justify-content:space-between;align-items:center;margin-bottom:min(20px,3vh);'>" &
			"<div style='display:flex;align-items:center;gap:8px;font-size:min(14px,3vw);font-weight:600;'><svg width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#4ADE80' stroke-width='2' stroke-linecap='round'><polyline points='22 12 18 12 15 21 9 3 6 12 2 12'/></svg>Saúde do Sistema</div>" &
			"<div class='pulse' style='width:8px;height:8px;border-radius:50%;background:#4ADE80;box-shadow:0 0 12px rgba(74,222,128,0.4);'></div></div>" &
			"<div style='display:grid;grid-template-columns:1fr 1fr;gap:min(16px,3vh);'>" &
			"<div class='fi' style='animation-delay:0.1s;'><p style='margin:0 0 4px;font-size:min(11px,2.5vw);color:#6B7280;'>Uptime</p><div style='font-size:min(20px,4.5vw);font-weight:600;color:#4ADE80;'>99.9%</div></div>" &
			"<div class='fi' style='animation-delay:0.2s;'><p style='margin:0 0 4px;font-size:min(11px,2.5vw);color:#6B7280;'>Latência</p><div style='font-size:min(20px,4.5vw);font-weight:600;color:#06B6D4;'>42ms</div></div>" &
			"<div class='fi' style='animation-delay:0.3s;'><p style='margin:0 0 4px;font-size:min(11px,2.5vw);color:#6B7280;'>Erros/min</p><div style='font-size:min(20px,4.5vw);font-weight:600;color:#F87171;'>0.3</div></div>" &
			"<div class='fi' style='animation-delay:0.4s;'><p style='margin:0 0 4px;font-size:min(11px,2.5vw);color:#6B7280;'>Req/seg</p><div style='font-size:min(20px,4.5vw);font-weight:600;color:#8B5CF6;'>1.2k</div></div>" &
			"</div></div></div>"
		lineageTag: 55555555-5555-5555-5555-555555555555

	measure HtmlGaugeCard =
			VAR _satisf = [Satisfacao] * 100
			VAR _dashoffset = 339.292 * (1 - _satisf / 100)
			RETURN
			"<style>@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}@keyframes dr{from{stroke-dashoffset:339.292}}@keyframes gp{0%,100%{text-shadow:0 0 15px rgba(6,182,212,0.3)}50%{text-shadow:0 0 30px rgba(6,182,212,0.8)}}.gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#6366F1,#06B6D4,#4ADE80,#6366F1);background-size:300% 300%;animation:br 4s ease infinite}.gi{background:#0D0D1A;border-radius:18px}.ar{animation:dr 2s ease-out forwards}.gn{animation:gp 2s ease-in-out infinite}</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;padding:16px;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center;'>" &
			"<p style='margin:0 0 8px;font-size:min(12px,2.5vw);color:#6B7280;text-transform:uppercase;letter-spacing:1px;'>Satisfação do Cliente</p>" &
			"<div style='width:min(120px,30vw,30vh);height:min(120px,30vw,30vh);margin:0 auto 8px;position:relative;'>" &
			"<svg width='100%' height='100%' viewBox='0 0 120 120' style='transform:rotate(-90deg);'>" &
			"<defs><linearGradient id='gg' x1='0%' y1='0%' x2='100%' y2='0%'><stop offset='0%' style='stop-color:#6366F1;'/><stop offset='100%' style='stop-color:#06B6D4;'/></linearGradient></defs>" &
			"<circle cx='60' cy='60' r='54' fill='none' stroke='rgba(255,255,255,0.06)' stroke-width='8'/>" &
			"<circle class='ar' cx='60' cy='60' r='54' fill='none' stroke='url(#gg)' stroke-width='8' stroke-linecap='round' stroke-dasharray='339.292' stroke-dashoffset='" & FORMAT(_dashoffset, "0.0") & "'/>" &
			"</svg>" &
			"<div class='gn' style='position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);font-size:min(28px,6vw);font-weight:700;'>" & FORMAT(_satisf, "0.0") & "%</div></div>" &
			"<div style='display:flex;align-items:center;justify-content:center;gap:6px;margin:0;font-size:min(13px,2.5vw);color:#9CA3AF;'><svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#4ADE80' stroke-width='2' stroke-linecap='round'><polyline points='20 6 9 17 4 12'/></svg>Meta: 90% atingida</div></div></div>"
		lineageTag: 66666666-6666-6666-6666-666666666666

	measure HtmlAnimatedCard =
			VAR _receita = [TotalReceita]
			VAR _metaReceita = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Receita Total")
			VAR _pctReceita = DIVIDE(_receita, _metaReceita, 0) * 100
			VAR _usuarios = [UsuariosAtivos]
			VAR _metaUsuarios = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Usuários Ativos")
			VAR _pctUsuarios = DIVIDE(_usuarios, _metaUsuarios, 0) * 100
			VAR _satisf = [Satisfacao] * 100
			VAR _score = (_pctReceita + _pctUsuarios + _satisf) / 3
			RETURN
			"<style>" &
			"@keyframes br{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}" &
			"@keyframes gp{0%,100%{text-shadow:0 0 20px rgba(99,102,241,0.3)}50%{text-shadow:0 0 40px rgba(99,102,241,0.8),0 0 60px rgba(99,102,241,0.4)}}" &
			"@keyframes fb{from{width:0%}}" &
			"@keyframes fs{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}" &
			".gb{padding:2px;border-radius:20px;background:linear-gradient(270deg,#6366F1,#06B6D4,#EC4899,#8B5CF6);background-size:300% 300%;animation:br 4s ease infinite}" &
			".gi{background:#12121F;border-radius:18px;padding:min(24px,4vh) min(24px,4vw)}" &
			".gn{animation:gp 2s ease-in-out infinite}" &
			".ab{height:6px;border-radius:3px;animation:fb 1.5s ease-out forwards}" &
			".ar{animation:fs 0.5s ease-out both}" &
			"</style>" &
			"<div class='gb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;color:white;'>" &
			"<div class='gi' style='width:100%;height:100%;box-sizing:border-box;display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;align-items:center;gap:6px;margin:0 0 min(8px,1.5vh);'>" &
			"<svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#8B5CF6' stroke-width='2' stroke-linecap='round'><polyline points='23 6 13.5 15.5 8.5 10.5 1 18'/><polyline points='17 6 23 6 23 12'/></svg>" &
			"<span style='font-size:min(11px,2.5vw);text-transform:uppercase;letter-spacing:1px;color:rgba(255,255,255,0.5);'>Performance Score</span></div>" &
			"<div class='gn' style='font-size:min(48px,10vw);font-weight:700;margin-bottom:min(16px,3vh);'>" & FORMAT(_score, "0.0") & "<span style='font-size:min(20px,4vw);color:#8B5CF6;'>%</span></div>" &
			"<div class='ar' style='margin-bottom:min(10px,2vh);animation-delay:0.2s;'>" &
			"<div style='display:flex;justify-content:space-between;font-size:min(11px,2.5vw);color:#9CA3AF;margin-bottom:4px;'><span>Receita</span><span style='color:#4ADE80;'>" & FORMAT(_pctReceita, "0") & "%</span></div>" &
			"<div style='background:rgba(255,255,255,0.06);border-radius:3px;height:min(6px,1.2vh);'><div class='ab' style='width:" & FORMAT(_pctReceita, "0") & "%;background:linear-gradient(90deg,#4ADE80,#06B6D4);'></div></div></div>" &
			"<div class='ar' style='margin-bottom:min(10px,2vh);animation-delay:0.4s;'>" &
			"<div style='display:flex;justify-content:space-between;font-size:min(11px,2.5vw);color:#9CA3AF;margin-bottom:4px;'><span>Usuários</span><span style='color:#8B5CF6;'>" & FORMAT(_pctUsuarios, "0") & "%</span></div>" &
			"<div style='background:rgba(255,255,255,0.06);border-radius:3px;height:min(6px,1.2vh);'><div class='ab' style='width:" & FORMAT(_pctUsuarios, "0") & "%;background:linear-gradient(90deg,#8B5CF6,#6366F1);animation-delay:0.3s;'></div></div></div>" &
			"<div class='ar' style='animation-delay:0.6s;'>" &
			"<div style='display:flex;justify-content:space-between;font-size:min(11px,2.5vw);color:#9CA3AF;margin-bottom:4px;'><span>Satisfação</span><span style='color:#EC4899;'>" & FORMAT(_satisf, "0") & "%</span></div>" &
			"<div style='background:rgba(255,255,255,0.06);border-radius:3px;height:min(6px,1.2vh);'><div class='ab' style='width:" & FORMAT(_satisf, "0") & "%;background:linear-gradient(90deg,#EC4899,#F472B6);animation-delay:0.6s;'></div></div></div>" &
			"</div></div>"
		lineageTag: 77777777-7777-7777-7777-777777777777

	measure HtmlFilterDrawer =
			VAR _receita = [TotalReceita]
			VAR _usuarios = [UsuariosAtivos]
			VAR _satisf = [Satisfacao] * 100
			VAR _conversao = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Conversão")
			VAR _ticket = CALCULATE(SUM(SampleData[Valor]), SampleData[Categoria] = "Ticket Médio")
			RETURN
			"<style>" &
			"@keyframes slideIn{from{transform:translateX(30px);opacity:0}to{transform:translateX(0);opacity:1}}" &
			"@keyframes fadeUp{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}" &
			"@keyframes glowPulse{0%,100%{box-shadow:0 0 8px rgba(99,102,241,0.3)}50%{box-shadow:0 0 16px rgba(99,102,241,0.6)}}" &
			"@keyframes shimmer{0%{background-position:-200% 0}100%{background-position:200% 0}}" &
			".drawer{animation:slideIn 0.6s cubic-bezier(0.16,1,0.3,1) both}" &
			".fi{animation:fadeUp 0.5s ease-out both}" &
			".chip{display:inline-block;padding:6px 14px;border-radius:8px;font-size:12px;font-weight:500}" &
			".chip-on{background:rgba(99,102,241,0.15);color:#818CF8;border:1px solid rgba(99,102,241,0.3)}" &
			".chip-off{background:rgba(255,255,255,0.04);color:#6B7280;border:1px solid rgba(255,255,255,0.06)}" &
			".ind{display:flex;align-items:center;justify-content:space-between;padding:12px 16px;background:rgba(255,255,255,0.03);border-radius:12px;border:1px solid rgba(255,255,255,0.05)}" &
			"</style>" &
			"<div class='drawer' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:linear-gradient(180deg,#1e1e2d 0%,#191927 100%);border-left:1px solid rgba(255,255,255,0.06);overflow-y:auto;'>" &
			"<div style='padding:24px;'>" &
			"<div class='fi' style='display:flex;justify-content:space-between;align-items:center;margin-bottom:24px;animation-delay:0.1s;'>" &
			"<div style='display:flex;align-items:center;gap:10px;'>" &
			"<div style='width:32px;height:32px;border-radius:10px;background:linear-gradient(135deg,rgba(99,102,241,0.2),rgba(6,182,212,0.2));display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='#818CF8' stroke-width='2' stroke-linecap='round'><polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3'/></svg></div>" &
			"<span style='font-size:16px;font-weight:600;color:#fff;'>Segmentação</span></div>" &
			"<div style='width:28px;height:28px;border-radius:8px;background:rgba(255,255,255,0.05);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#6B7280' stroke-width='2' stroke-linecap='round'><line x1='18' y1='6' x2='6' y2='18'/><line x1='6' y1='6' x2='18' y2='18'/></svg></div></div>" &
			"<div style='height:1px;background:linear-gradient(90deg,transparent,rgba(99,102,241,0.2),transparent);margin-bottom:24px;'></div>" &
			"<div class='fi' style='margin-bottom:24px;animation-delay:0.2s;'>" &
			"<div style='font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:#565674;margin-bottom:12px;font-weight:600;'>Categorias</div>" &
			"<div style='display:flex;flex-wrap:wrap;gap:8px;'>" &
			"<span class='chip chip-on'>Receita</span>" &
			"<span class='chip chip-on'>Usuários</span>" &
			"<span class='chip chip-off'>Satisfação</span>" &
			"<span class='chip chip-off'>Conversão</span>" &
			"<span class='chip chip-off'>Ticket</span>" &
			"</div></div>" &
			"<div class='fi' style='margin-bottom:24px;animation-delay:0.3s;'>" &
			"<div style='font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:#565674;margin-bottom:12px;font-weight:600;'>Período</div>" &
			"<div style='display:flex;gap:8px;'>" &
			"<div style='flex:1;padding:10px 14px;background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);border-radius:10px;text-align:center;'>" &
			"<div style='font-size:10px;color:#818CF8;margin-bottom:2px;'>De</div>" &
			"<div style='font-size:13px;color:#fff;font-weight:500;'>Jan 2026</div></div>" &
			"<div style='flex:1;padding:10px 14px;background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);border-radius:10px;text-align:center;'>" &
			"<div style='font-size:10px;color:#818CF8;margin-bottom:2px;'>Até</div>" &
			"<div style='font-size:13px;color:#fff;font-weight:500;'>Jul 2026</div></div>" &
			"</div></div>" &
			"<div class='fi' style='margin-bottom:16px;animation-delay:0.4s;'>" &
			"<div style='font-size:11px;text-transform:uppercase;letter-spacing:1.5px;color:#565674;margin-bottom:12px;font-weight:600;'>Indicadores</div>" &
			"<div style='display:flex;flex-direction:column;gap:8px;'>" &
			"<div class='ind'><div style='display:flex;align-items:center;gap:10px;'><div style='width:8px;height:8px;border-radius:50%;background:#6366F1;box-shadow:0 0 8px rgba(99,102,241,0.4);'></div><span style='font-size:13px;color:#9CA3AF;'>Receita</span></div><span style='font-size:14px;font-weight:600;color:#fff;'>R$ " & FORMAT(_receita, "#,##0") & "</span></div>" &
			"<div class='ind'><div style='display:flex;align-items:center;gap:10px;'><div style='width:8px;height:8px;border-radius:50%;background:#06B6D4;box-shadow:0 0 8px rgba(6,182,212,0.4);'></div><span style='font-size:13px;color:#9CA3AF;'>Usuários</span></div><span style='font-size:14px;font-weight:600;color:#fff;'>" & FORMAT(_usuarios, "#,##0") & "</span></div>" &
			"<div class='ind'><div style='display:flex;align-items:center;gap:10px;'><div style='width:8px;height:8px;border-radius:50%;background:#4ADE80;box-shadow:0 0 8px rgba(74,222,128,0.4);'></div><span style='font-size:13px;color:#9CA3AF;'>Satisfação</span></div><span style='font-size:14px;font-weight:600;color:#fff;'>" & FORMAT(_satisf, "0.0") & "%</span></div>" &
			"<div class='ind'><div style='display:flex;align-items:center;gap:10px;'><div style='width:8px;height:8px;border-radius:50%;background:#F59E0B;box-shadow:0 0 8px rgba(245,158,11,0.4);'></div><span style='font-size:13px;color:#9CA3AF;'>Conversão</span></div><span style='font-size:14px;font-weight:600;color:#fff;'>" & FORMAT(_conversao, "0.0") & "%</span></div>" &
			"<div class='ind'><div style='display:flex;align-items:center;gap:10px;'><div style='width:8px;height:8px;border-radius:50%;background:#EC4899;box-shadow:0 0 8px rgba(236,72,153,0.4);'></div><span style='font-size:13px;color:#9CA3AF;'>Ticket Médio</span></div><span style='font-size:14px;font-weight:600;color:#fff;'>R$ " & FORMAT(_ticket, "#,##0") & "</span></div>" &
			"</div></div>" &
			"<div style='height:2px;background:linear-gradient(90deg,#6366F1,#06B6D4,#EC4899);border-radius:2px;margin-top:16px;'></div>" &
			"</div></div>"
		lineageTag: 88888888-8888-8888-8888-888888888888

	measure HtmlFilterButton =
			"<style>" &
			"@keyframes borderGlow{0%{background-position:0% 50%}50%{background-position:100% 50%}100%{background-position:0% 50%}}" &
			"@keyframes iconPulse{0%,100%{opacity:0.8}50%{opacity:1}}" &
			".fb{padding:2px;border-radius:12px;background:linear-gradient(270deg,#6366F1,#06B6D4,#6366F1);background-size:200% 200%;animation:borderGlow 3s ease infinite}" &
			".fbi{background:#1e1e2d;border-radius:10px;width:100%;height:100%;display:flex;align-items:center;justify-content:center}" &
			".fbi svg{animation:iconPulse 2s ease-in-out infinite}" &
			"</style>" &
			"<div class='fb' style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;'>" &
			"<div class='fbi'>" &
			"<svg width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='#818CF8' stroke-width='2' stroke-linecap='round'>" &
			"<polygon points='22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3'/>" &
			"</svg></div></div>"
		lineageTag: 99999999-9999-9999-9999-999999999999

	measure ExecKpiReceita =
			VAR _val = [TotalReceita]
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Receita Total")
			VAR _pct = DIVIDE(_val, _meta, 0) * 100
			VAR _up = _val >= _meta
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#14142B;border-radius:16px;border:1px solid rgba(99,102,241,.15);padding:clamp(12px,3vh,20px);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;align-items:center;gap:6px;margin-bottom:8px;'>" &
			"<div style='width:28px;height:28px;border-radius:8px;background:rgba(99,102,241,.15);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#6366F1' stroke-width='2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg></div>" &
			"<span style='font-size:min(10px,2.2vw);text-transform:uppercase;letter-spacing:1px;color:#6B7280;'>Receita</span></div>" &
			"<div style='font-size:min(26px,5.5vw);font-weight:700;color:#fff;margin-bottom:6px;'>R$ " & FORMAT(_val / 1000, "#,##0") & "K</div>" &
			"<div style='display:flex;align-items:center;gap:6px;'>" &
			"<div style='padding:2px 8px;border-radius:6px;font-size:min(11px,2.4vw);font-weight:600;" & IF(_up, "background:rgba(74,222,128,.12);color:#4ADE80;'>▲ ", "background:rgba(248,113,113,.12);color:#F87171;'>▼ ") & FORMAT(_pct, "0.0") & "%</div>" &
			"<span style='font-size:min(10px,2.2vw);color:#6B7280;'>da meta</span></div></div>"
		lineageTag: e1000001-exec-4001-a001-000000000001

	measure ExecKpiUsuarios =
			VAR _val = [UsuariosAtivos]
			VAR _meta = CALCULATE(SUM(SampleData[Meta]), SampleData[Categoria] = "Usuários Ativos")
			VAR _pct = DIVIDE(_val, _meta, 0) * 100
			VAR _up = _val >= _meta
			RETURN
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#14142B;border-radius:16px;border:1px solid rgba(6,182,212,.15);padding:clamp(12px,3vh,20px);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;align-items:center;gap:6px;margin-bottom:8px;'>" &
			"<div style='width:28px;height:28px;border-radius:8px;background:rgba(6,182,212,.15);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#06B6D4' stroke-width='2'><path d='M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2'/><circle cx='9' cy='7' r='4'/><path d='M23 21v-2a4 4 0 0 0-3-3.87'/><path d='M16 3.13a4 4 0 0 1 0 7.75'/></svg></div>" &
			"<span style='font-size:min(10px,2.2vw);text-transform:uppercase;letter-spacing:1px;color:#6B7280;'>Usuários</span></div>" &
			"<div style='font-size:min(26px,5.5vw);font-weight:700;color:#fff;margin-bottom:6px;'>" & FORMAT(_val, "#,##0") & "</div>" &
			"<div style='display:flex;align-items:center;gap:6px;'>" &
			"<div style='padding:2px 8px;border-radius:6px;font-size:min(11px,2.4vw);font-weight:600;" & IF(_up, "background:rgba(74,222,128,.12);color:#4ADE80;'>▲ ", "background:rgba(248,113,113,.12);color:#F87171;'>▼ ") & FORMAT(_pct, "0.0") & "%</div>" &
			"<span style='font-size:min(10px,2.2vw);color:#6B7280;'>da meta</span></div></div>"
		lineageTag: e1000002-exec-4002-a002-000000000002

	measure ExecKpiSatisfacao =
			VAR _val = [Satisfacao] * 100
			VAR _meta = 90
			VAR _up = _val >= _meta
			RETURN
			"<style>@keyframes fb{from{width:0%}}.ab{animation:fb 1.5s ease-out forwards}</style>" &
			"<div style='width:100%;height:100vh;box-sizing:border-box;font-family:Segoe UI,sans-serif;background:#14142B;border-radius:16px;border:1px solid rgba(74,222,128,.15);padding:clamp(12px,3vh,20px);display:flex;flex-direction:column;justify-content:center;'>" &
			"<div style='display:flex;align-items:center;gap:6px;margin-bottom:8px;'>" &
			"<div style='width:28px;height:28px;border-radius:8px;background:rgba(74,222,128,.15);display:flex;align-items:center;justify-content:center;'>" &
			"<svg width='14' height='14' viewBox='0 0 24 24' fill='none' stroke='#4ADE80' stroke-width='2'><path d='M14 9V5a3 3 0 0 0-3-3l-4 9v11h11.28a2 2 0 0 0 2-1.7l1.38-9a2 2 0 0 0-2-2.3H14z'/></svg></div>" &
			"<span style='font-size:min(10px,2.2vw);text-transform:uppercase;letter-spacing:1px;color:#6B7280;'>Satisfação</span></div>" &
			"<div style='font-size:min(26px,5.5vw);font-weight:700;color:#fff;margin-bottom:8px;'>" & FORMAT(_val, "0.0") & "%</div>" &
			"<div style='background:rgba(255,255,255,.06);border-radius:4px;height:6px;overflow:hidden;'>" &
			"<div class='ab' style='width:" & FORMAT(_val, "0") & "%;height:100%;border-radius:4px;background:linear-gradient(90deg,#4ADE80,#06B6D4);'></div></div>" &
			"<div style='display:flex;justify-content:space-between;margin-top:4px;font-size:min(10px,2.2vw);color:#6B7280;'><span>Meta: " & FORMAT(_meta, "0") & "%</span><span style='color:" & IF(_up, "#4ADE80", "#F87171") & ";'>" & IF(_up, "✓ Atingida", "✗ Abaixo") & "</span></div></div>"
		lineageTag: e1000003-exec-4003-a003-000000000003

	measure ExecNavIcons =
			"<div style='display:flex;gap:8px;height:100vh;align-items:center;justify-content:center;font-family:Segoe UI,sans-serif;'>" &
			"<div style='width:36px;height:36px;border-radius:10px;background:rgba(99,102,241,.12);display:flex;align-items:center;justify-content:center;' title='SnowUI'><svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='#818CF8' stroke-width='2'><path d='M12 2v20M2 12h20M4.93 4.93l14.14 14.14M19.07 4.93L4.93 19.07'/></svg></div>" &
			"<div style='width:36px;height:36px;border-radius:10px;background:rgba(6,182,212,.12);display:flex;align-items:center;justify-content:center;' title='Sales'><svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='#22D3EE' stroke-width='2'><line x1='12' y1='1' x2='12' y2='23'/><path d='M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6'/></svg></div>" &
			"<div style='width:36px;height:36px;border-radius:10px;background:rgba(74,222,128,.12);display:flex;align-items:center;justify-content:center;' title='Analytics'><svg width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='#4ADE80' stroke-width='2'><rect x='3' y='12' width='4' height='9' rx='1'/><rect x='10' y='6' width='4' height='15' rx='1'/><rect x='17' y='2' width='4' height='19' rx='1'/></svg></div></div>"
		lineageTag: e1000006-exec-4006-a006-000000000006

	column Categoria
		lineageTag: 5ec4e79d-2d81-4d04-b046-059afcfc1e2b
		isNameInferred
		sourceColumn: [Categoria]

	column Valor
		lineageTag: 0d1c680f-3434-44e3-ac26-4477a6d25b08
		isNameInferred
		sourceColumn: [Valor]

	column Meta
		lineageTag: 62fa42dd-2955-4e43-ba58-9c2e811c5c90
		isNameInferred
		sourceColumn: [Meta]

	partition SampleData = calculated
		mode: import
		source =
				DATATABLE(
					"Categoria", STRING,
					"Valor", DOUBLE,
					"Meta", DOUBLE,
					{
						{"Receita Total", 1250000, 1000000},
						{"Usuários Ativos", 8432, 10000},
						{"Satisfação", 94.5, 90},
						{"Conversão", 12.8, 15},
						{"Ticket Médio", 285.50, 250}
					}
				)

